# .github/workflows/deploy.yml
name: Build and Deploy Nuxt Site

on:
  push:
    branches:
      - main

# Variable de entorno para desactivar la telemetría de Nuxt
env:
  NUXT_TELEMETRY_DISABLED: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. Obtiene tu código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configura Node.js (Actualizado a v20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Actualizado a Node 20
          cache: 'npm'

      # 3. (NUEVO) Instala herramientas de compilación
      # Esto le da a la máquina las herramientas para compilar "native bindings"
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # 4. Instala dependencias y compila
      - name: Install and Build
        run: npm install --omit=optional
          npm run generate

      # 5. Envía la carpeta compilada a la rama 'build'
      - name: Deploy to Build Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          publish_branch: build
          force_orphan: true
